
export class CareerDB {
  constructor() {
    this.calendarData =
    {
      calendar: {
        'Январь': [{ day: 1, data: { match: 'Соперник' } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 31, data: { match: false } }],
        'Февраль': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }],
        'Март': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 31, data: { match: false } }],
        'Апрель': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 30, data: { match: false } }],
        'Май': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 31, data: { match: false } }],
        'Июнь': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 30, data: { match: false } }],
        'Июль': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 31, data: { match: false } }],
        'Август': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 31, data: { match: false } }],
        'Сентябрь': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 30, data: { match: false } }],
        'Октябрь': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 31, data: { match: false } }],
        'Ноябрь': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 30, data: { match: false } }],
        'Декабрь': [{ day: 1, data: { match: false } }, { day: 2, data: { match: false } }, { day: 3, data: { match: false } }, { day: 4, data: { match: false } }, { day: 5, data: { match: false } }, { day: 6, data: { match: false } }, { day: 7, data: { match: false } }, { day: 8, data: { match: false } }, { day: 9, data: { match: false } }, { day: 10, data: { match: false } }, { day: 11, data: { match: false } }, { day: 12, data: { match: false } }, { day: 13, data: { match: false } }, { day: 14, data: { match: false } }, { day: 15, data: { match: false } }, { day: 16, data: { match: false } }, { day: 17, data: { match: false } }, { day: 18, data: { match: false } }, { day: 19, data: { match: false } }, { day: 20, data: { match: false } }, { day: 21, data: { match: false } }, { day: 22, data: { match: false } }, { day: 23, data: { match: false } }, { day: 24, data: { match: false } }, { day: 25, data: { match: false } }, { day: 26, data: { match: false } }, { day: 27, data: { match: false } }, { day: 28, data: { match: false } }, { day: 29, data: { match: false } }, { day: 30, data: { match: false } }, { day: 31, data: { match: false } }],
      }
    }
    this.leagues = {
      'Russia': {
        teams: {
          'Зенит Казань': {
            skill: 70
          },
          'Белогорье': {
            skill: 69
          },
          'Динамо': {
            skill: 68
          },
          'Локомотив': {
            skill: 67
          },
          'Зенит СПб': {
            skill: 66
          },
          'Динамо-ЛО': {
            skill: 66
          },
          'Динамо-Урал': {
            skill: 66
          },
          'Енисей': {
            skill: 66
          },
          'Кузбасс': {
            skill: 66
          },
          'Факел-Ямал': {
            skill: 66
          },
          'Газпром-Югра': {
            skill: 66
          },
          'АСК': {
            skill: 66
          },
          'Оренбуржье': {
            skill: 66
          },
          'Нова': {
            skill: 66
          },
          'МГТУ': {
            skill: 66
          }
        }

      }
    }

  }
}